### ISSUE TITLE
InitializationError when running JUnit: java.lang.IllegalAccessError: tried to access method org.junit.runners.BlockJUnit4ClassRunner.validateFields(Ljava/util/List;)V from class junitparams.JUnitParamsRunner

### ISSUE THREAD

**Issue by perwestling** [Pragmatists/JUnitParams#102]
Hi,

I have a background using TestNG and have seen a need for a better parameterized test in JUnit. After googling I found JUnitParams that looks promising. 
But I have a problem. If I try to use it I get initialization error:
<code>
<pre>
java.lang.IllegalAccessError: tried to access method org.junit.runners.BlockJUnit4ClassRunner.validateFields(Ljava/util/List;)V from class junitparams.JUnitParamsRunner
	at junitparams.JUnitParamsRunner.collectInitializationErrors(JUnitParamsRunner.java:405)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:344)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:74)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:55)
	at junitparams.JUnitParamsRunner.<init>(JUnitParamsRunner.java:393)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
</pre>
</code>
I have copied PersonTest from <a href="https://github.com/Pragmatists/JUnitParams/tree/master/src/test/java/junitparams/usage/person_example">https://github.com/Pragmatists/JUnitParams/tree/master/src/test/java/junitparams/usage/person_example</a>
and I use the following versions (in Gradle format):
<pre>
         testCompile 'junit:junit:4.10'
         testCompile 'pl.pragmatists:JUnitParams:1.0.5'
         testCompile 'org.assertj:assertj-core:3.6.1'
</pre>
And I use java JDK 1.8.0_72.

Here is the top of PersonTest (same as from resource mentioned above, just a different package).
<code>
<pre>
package examples.personExample;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;
import org.junit.runner.RunWith;

import junitparams.JUnitParamsRunner;
import junitparams.Parameters;
import junitparams.naming.TestCaseName;

@RunWith(JUnitParamsRunner.class)
public class PersonTest {

  @Test
  @Parameters({
      "17, false",
      "22, true"})
  public void isAdultAgeDirect(int age, boolean valid) throws Exception {
    assertThat(new Person(age).isAdult()).isEqualTo(valid);
  }

  @Test
  @Parameters(method = "adultValues")
  public void isAdultAgeDefinedMethod(int age, boolean valid) throws Exception {
    assertThat(new Person(age).isAdult()).isEqualTo(valid);
  }
</pre>
</code>

Have also tried to debug this but it seems hard to pinpoint the problem.
Did get same initializationError when just adding JUnitParamsRunner and @Parameters to an existing test case.

So, have I missed anything obvious?

/ Per Westling, Sweden

**Comment by pikondrej** [comment]
You are probably experiencing the same problem as https://github.com/Pragmatists/JUnitParams/issues/52. There is a code sample of class extending JUnitParamsRunner that you use in @RunWith annotation.

**Comment by perwestling** [comment]
Thanks for the answer.
In my case I run the whole test class in Eclipse.
Tried to use MyJUnitParamsRunner and the modified @TestCaseName but got the same exception.
The stack trace do contain MyJUnitParamsRunner:
<code><pre>java.lang.IllegalAccessError: tried to access method org.junit.runners.BlockJUnit4ClassRunner.validateFields(Ljava/util/List;)V from class junitparams.JUnitParamsRunner
	at junitparams.JUnitParamsRunner.collectInitializationErrors(JUnitParamsRunner.java:405)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:344)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:74)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:55)
	at junitparams.JUnitParamsRunner.<init>(JUnitParamsRunner.java:393)
	at examples.MyJUnitParamsRunner.<init>(MyJUnitParamsRunner.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)</pre></code>
 

BTW, I tried to run just one method in the test class and it fails but with slightly different symptom. Now I get one line with InitializationError in the run result window, and if I click on that I end up in org.junit.runner.manipulation.Filter... 

I have not spent that much time one this issue, as I am just taking a quick test to see if JUnitParams is something that I could use. If I get time I will look deeper into this.

**Comment by pikondrej** [comment]
I was able to make it work, so there must be some other problem. What version of Eclipse do you use? Try the latest version, if you're not already using it.

**Comment by peterjurkovic** [comment]
Hi, 
I've tried an example listed https://github.com/Pragmatists/JUnitParams/tree/master/src/test/java/junitparams/usage/person_example and all tests passes with no error. 

I've used:
```
testCompile 'junit:junit:4.12'
testCompile 'pl.pragmatists:JUnitParams:1.0.5'
testCompile 'org.assertj:assertj-core:2.2.0'
```
and Eclipse Version: Neon.2 Release (4.6.2)

**Comment by perwestling** [comment]
I was using Mars.2 Release (4.5.2). Did try to run Neon (4.6.1) instead and got the same problem.
So I tried the same outside Eclipse and got the same exception.

Then I tried to use the same versions as @peterjurkovic and still got same.
Finally I tried to remove the powermock dependency.... but no change.

It seems to be something in my environment that is the problem. As this is a nice-to-have feature but not essential (have solved it in another, but more crude, way) I will postpone this and see if I have the time to dig further in the future.

If I do find out the problem in the future, I will try to update this ticket. 

Thanks for support

/ Per

**Comment by peterjurkovic** [comment]
I think so. `IllegalAccessError` - Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

**Comment by PathriK** [comment]
I think the error has something to with version compatibility. Created a sample Eclipse Java Maven project with just a single test method that just prints to console. Got this error for following versions added through maven dependency:

`JUnitParams: 1.0.6
junit: 4.8.2`

But when I removed the junit dependency and ran the test, error did not happen and test went fine. I guess, when a project uses old junit, this error occurs.

**Comment by PathriK** [comment]
On analyzing more, the issue seems to be occurring on junit versions from and before 4.10. Till v4.10, `validateFields` method was had access modifier as `private` and was changed to `protected` afterwards. This is causing the illegal access error when we use a older junit with the latest JUnitParams

**Comment by adammichalik** [comment]
+1 for @PathriK - I answered a question on the same issue here: https://stackoverflow.com/a/42808474/466738
JUnitParams 1.0.6 requires JUnit 4.12. Make sure you are not overriding this version in your project.

**Comment by priyankasabharwal81** [comment]
I have Junit 4.12 Installed and I am getting the same problem. Java version is 1.8.0_202
