### ISSUE TITLE
1.0.6 breaks method handling with complex Collection parameter types

### ISSUE THREAD

**Issue by ukcrpb6** [Pragmatists/JUnitParams#106]
Given the following:

```java
import com.google.common.base.Splitter;
import com.google.common.collect.ImmutableList;

import junitparams.JUnitParamsRunner;
import junitparams.Parameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Collection;
import java.util.List;

/**
 * Test failing collection usage of parameters annotation.
 */
@RunWith(JUnitParamsRunner.class)
public class BreakerTest {

  @Test
  @Parameters(method = "words")
  public void testBreakage(Collection<String> strings) throws Exception {
    System.out.println(strings);
  }

  private ImmutableList<List<String>> words() {
    return ImmutableList.of(
        Splitter.on(' ').splitToList("Just the place for a Snark!"),
        Splitter.on(' ').splitToList("The Bellman cried, as he carried his crew with care"),
        Splitter.on(' ').splitToList("Supporting each man on the top of the tide,"),
        Splitter.on(' ').splitToList("By a finger entwined in his hair.")
    );
  }
}
```
# 1.0.5

The test runs successfully producing:

```
[Just, the, place, for, a, Snark!]
[The, Bellman, cried,, as, he, carried, his, crew, with, care]
[Supporting, each, man, on, the, top, of, the, tide,]
[By, a, finger, entwined, in, his, hair.]
```

# 1.0.6+

The test fails producing:

```
java.lang.IllegalStateException: While trying to create object of class class java.util.ArrayList could not find constructor with arguments matching (type-wise) the ones given in parameters.

	at junitparams.internal.InvokeParameterisedMethod.createObjectOfExpectedTypeBasedOnParams(InvokeParameterisedMethod.java:85)
	at junitparams.internal.InvokeParameterisedMethod.castParamsFromObjects(InvokeParameterisedMethod.java:67)
	at junitparams.internal.InvokeParameterisedMethod.<init>(InvokeParameterisedMethod.java:38)
	at junitparams.internal.ParameterisedTestClassRunner.buildMethodInvoker(ParameterisedTestClassRunner.java:125)
	at junitparams.internal.ParameterisedTestClassRunner.parameterisedMethodInvoker(ParameterisedTestClassRunner.java:118)
	at junitparams.JUnitParamsRunner.methodInvoker(JUnitParamsRunner.java:448)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:273)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:417)
	at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:386)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NoSuchMethodException: java.util.ArrayList.<init>(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at junitparams.internal.InvokeParameterisedMethod.createObjectOfExpectedTypeBasedOnParams(InvokeParameterisedMethod.java:82)
	... 24 more
```

it should be noted that replacing the words method with 

```
private List<String>[] words() {
    return new List[]{
        Splitter.on(' ').splitToList("Just the place for a Snark!"),
        Splitter.on(' ').splitToList("The Bellman cried, as he carried his crew with care"),
        Splitter.on(' ').splitToList("Supporting each man on the top of the tide,"),
        Splitter.on(' ').splitToList("By a finger entwined in his hair.")
    };
  }
```

still works

**Comment by jrmichael** [comment]
Thx @ukcrpb6 for issuing a bug and a fix.
