### ISSUE TITLE
Automatic class name to class object conversion

### ISSUE THREAD

**Issue by adammichalik** [Pragmatists/JUnitParams#41]
JUnitParams supports most of the literals - numeric, enums, strings, but class names are not automatically converted:
```
    @Test
    @Parameters({"java.lang.Exception"})
    public void testException(Class<?> e) {...}
```
fails with
```
java.lang.IllegalArgumentException: Parameter type (java.lang.Class) cannot be handled! Only primitive types and Strings can be used.
	at junitparams.internal.InvokeParameterisedMethod.castParameterDirectly(InvokeParameterisedMethod.java:192)
	at junitparams.internal.InvokeParameterisedMethod.castAllParametersToProperTypes(InvokeParameterisedMethod.java:143)
	at junitparams.internal.InvokeParameterisedMethod.castParamsUsingConverters(InvokeParameterisedMethod.java:104)
	at junitparams.internal.InvokeParameterisedMethod.castParamsFromString(InvokeParameterisedMethod.java:45)
```
It would be nice to see that working :)

**Comment by michal-lipski** [comment]
Totally agree. We are looking forward for your PR :)

**Comment by adammichalik** [comment]
There you go :)

**Comment by michal-lipski** [comment]
That was fast :)

**Comment by adammichalik** [comment]
Well, it sounded line a challenge ;) Thanks!
