### ISSUE TITLE
Cannot find invoker for the parameterised method. Using wrong JUnit version?

### ISSUE THREAD

**Issue by erikmollink** [Pragmatists/JUnitParams#44]
Using jUnit 4.11 and jUnitParams 1.0.4

```
java.lang.RuntimeException: Cannot find invoker for the parameterised method. Using wrong JUnit version?
    at junitparams.internal.ParameterisedTestMethodRunner.findParameterisedMethodInvokerInChain(ParameterisedTestMethodRunner.java:71)
    at junitparams.internal.ParameterisedTestMethodRunner.findChildForParams(ParameterisedTestMethodRunner.java:58)
    at junitparams.internal.ParameterisedTestMethodRunner.runTestMethod(ParameterisedTestMethodRunner.java:39)
    at junitparams.internal.ParameterisedTestClassRunner.runParameterisedTest(ParameterisedTestClassRunner.java:143)
    at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:405)
    at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:383)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by erichosick** [comment]
I was also having this problem. It turned out I had an error in the constructor for the test class and the error was being passed to InvokeParameterisedMethod findParameterisedMethodInvokerInChain(Statement methodInvoker) { ... }. The value of methodInvoker was an Exception.

Put a break point in findParameterisedMethodInvokerInChain and see what value methodInvoker is.

The issue here is that findParameterisedMethodInvokerInChain is masking the real error.

Hope this helps.

**Comment by sergiords** [comment]
It helped me. Thanks for your comment.

**Comment by netbrain** [comment]
+1

**Comment by sharmasourabh** [comment]
If you are using JUnit 5, then make sure you keep public access modifier in place for both class and method.
