### ISSUE TITLE
Regression: NPE on null arrays in the parameters

### ISSUE THREAD

**Issue by meseer** [Pragmatists/JUnitParams#56]
Following code snippet used to work on 1.0.2 and fails on 1.0.4
```java
    private Object nullArray() {
        return new Object[] {/*is null*/  /* array */
                new Object[] { false,     new String[] { "1", "2" } },
                new Object[] { true ,     null },
        };
    }

    @Test
    @Parameters(method = "nullArray")
    public void testNullArraysArePassedIn(boolean isNullArray, String[] array) throws Exception {
        Assert.assertEquals(isNullArray, array == null);
    }
```

Error message is the following: 
```
[junit]      java.lang.NullPointerException
[junit]          at junitparams.internal.InvokeParameterisedMethod.createArrayOfTypesOf(InvokeParameterisedMethod.java:90)
[junit]          at junitparams.internal.InvokeParameterisedMethod.castParamsFromObjects(InvokeParameterisedMethod.java:62)
[junit]          at junitparams.internal.InvokeParameterisedMethod.<init>(InvokeParameterisedMethod.java:34)
[junit]          at junitparams.internal.ParameterisedTestClassRunner.buildMethodInvoker(ParameterisedTestClassRunner.java:125)
[junit]          at junitparams.internal.ParameterisedTestClassRunner.parameterisedMethodInvoker(ParameterisedTestClassRunner.java:119)
[junit]          at junitparams.JUnitParamsRunner.methodInvoker(JUnitParamsRunner.java:434)
[junit]          at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:414)
[junit]          at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:385) 
```

**Comment by bennetelli** [comment]
I just tried it with the current master which is also of version 1.0.4 and I get an Exception with error message:"should have no parameters" instead of your NPE.

**Comment by jrmichael** [comment]
thx @bennetelli

**Comment by meseer** [comment]
Thanks!
